# DBplus Copyright (C) 2011 Rafael Dantas Justo
#
# This file is part of DBplus.
#
# DBplus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DBplus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DBplus.  If not, see <http://www.gnu.org/licenses/>.

Import("env", "libraryPath", "localBinInstall", "getLibraries")

localLibraries = getLibraries(["DBPLUS"])
localLibraries.extend(["boost_unit_test_framework"])

test = env.Program("test", 
                   ["Main.cpp", "MySqlTest.cpp"], 
                   LIBS = localLibraries, LIBPATH = libraryPath)
env.Test("test.passed", test)
