# DBplus Copyright (C) 2011 Rafael Dantas Justo
#
# This file is part of DBplus.
#
# DBplus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DBplus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DBplus.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

Import("env", "basePath", "localLibraryInstall")

sys.path.append(basePath + "/install")
import installer

dbplusName = localLibraryInstall + "/" + os.getcwd().split("/")[-1]
dbplusLib = env.StaticLibrary(dbplusName, Glob("*.cpp") + Glob("database/*.cpp"))

opts = Variables(basePath + "/conf/dbplus.conf", ARGUMENTS)
installer.AddOptions(opts)
opts.Update(env)

install = installer.Installer(env)
install.AddLibrary(dbplusLib)
install.AddHeaders(basePath + "/include/dbplus", "*.hpp", "", True)
